theme: minima

title: Mafal-Día
description: >-
  Mafal-Día! Una historieta de Mafalda, todos los días

repository: fdelmazo/mafal-dia
email1: federicodelmazo@hotmail.com
email2: florrr1997@gmail.com

githubuser1: FdelMazo
githubuser2: Florencia-97

markdown: kramdown
plugins:
  - jekyll-github-metadata
  - jekyll-feed

baseurl: https://fdelmazo.github.io/Mafal-Dia