theme: minima

title: Mafalda
description: Tira a Tira

email1: federicodelmazo@hotmail.com
email2: florrr1997@gmail.com

githubuser1: FdelMazo
githubuser2: Florencia-97

markdown: kramdown
plugins:
  - jekyll-github-metadata
