theme: minima

title: Mafalda Tira a Tira
description: Una historieta de Mafalda, todos los días

email1: federicodelmazo@hotmail.com
email2: florrr1997@gmail.com

githubuser1: FdelMazo
githubuser2: Florencia-97

markdown: kramdown
plugins:
  - jekyll-github-metadata
